name: Deploy to Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: live
    env:
      GCP_CLOUD_RUN_REGION: europe-west1
      GCP_DOMAIN: "ld51-server.jam.dsg.li"
      GCP_IMAGE_NAME: shared/ld51-server
      GCP_IMAGE_REGISTRY: europe-west1-docker.pkg.dev
      GCP_RUN_SERVICE_ACCOUNT: "ld51-server-run@dsg-jam-366314.iam.gserviceaccount.com"
      GCP_SERVICE_ID: ld51-server

    steps:
      - uses: actions/checkout@v3

      - name: "Docker Auth: GitHub"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: gcp_auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Google Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          install_components: "beta"

      - name: "Docker Auth: GCP"
        run: gcloud auth configure-docker "${{ env.GCP_IMAGE_REGISTRY }}"

      - name: Generate Image Names
        id: image
        run: |-
          echo "github=ghcr.io/${{ github.repository }}:latest" >>"$GITHUB_OUTPUT"
          echo "gcp=${{ env.GCP_IMAGE_REGISTRY }}/${{ steps.gcp_auth.outputs.project_id }}/${{ env.GCP_IMAGE_NAME }}:${{ github.sha }}" >>"$GITHUB_OUTPUT"

      - name: Build and Push Images
        uses: docker/build-push-action@v3
        with:
          file: deploy/container/Dockerfile
          push: true
          tags: |
            ${{ steps.image.outputs.github }}
            ${{ steps.image.outputs.gcp }}

      - name: Prepare Service template
        env:
          SERVICE_ACCOUNT: "${{ env.GCP_RUN_SERVICE_ACCOUNT }}"
          IMAGE: "${{ steps.image.outputs.gcp }}"
        run: |
          gcloud config set run/region "${{ env.GCP_CLOUD_RUN_REGION }}"
          envsubst <deploy/knative/service.template.yaml >service.yaml

      - name: Deploy to Cloud Run
        run: gcloud run services replace service.yaml

      - name: Configure deployment
        run: |
          gcloud run services set-iam-policy "${{ env.GCP_SERVICE_ID }}" deploy/knative/gcp-iam-policy.yaml
          gcloud beta run domain-mappings create --force-override --service "${{ env.GCP_SERVICE_ID }}" --domain "${{ env.GCP_DOMAIN }}"
