name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: live
    env:
      GCP_CLOUD_RUN_REGION: europe-west1
      GCP_CLOUD_RUN_SERVICE: ld51-server
      GCP_IMAGE_NAME: shared/ld51-server
      GCP_IMAGE_REGISTRY: europe-west1-docker.pkg.dev

    steps:
      - uses: actions/checkout@v3

      - name: "Docker Auth: GitHub"
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - id: gcp_auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: "access_token"

      - name: "Docker Auth: GCP"
        uses: "docker/login-action@v1"
        with:
          registry: "${{ env.GCP_IMAGE_REGISTRY }}"
          username: "oauth2accesstoken"
          password: "${{ steps.gcp_auth.outputs.access_token }}"

      - name: Generate image names
        id: image
        run: |-
          echo "github=ghcr.io/${{ github.repository }}:latest" >>"$GITHUB_OUTPUT"
          echo "gcp=${{ env.GCP_IMAGE_REGISTRY }}/${{ env.GCP_IMAGE_NAME }}:${{ github.sha }}" >>"$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: deploy/container/Dockerfile
          push: true
          tags: "${{ steps.image.outputs.github }},${{ steps.image.outputs.gcp }}"

      - name: Deploy to Cloud Run
        id: deploy_cloud_run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.GCP_CLOUD_RUN_SERVICE }}
          region: ${{ env.GCP_CLOUD_RUN_REGION }}
          image: "${{ steps.image.outputs.gcp }}"
