name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: live

    steps:
      - uses: actions/checkout@v3

      - id: gcp_auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
          token_format: "access_token"

      - uses: "docker/login-action@v1"
        with:
          registry: "${{ secrets.GCP_IMAGE_REGISTRY }}"
          username: "oauth2accesstoken"
          password: "${{ steps.gcp_auth.outputs.access_token }}"

      - uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: deploy/container/Dockerfile
          push: true
          tags: "${{ secrets.GCP_IMAGE_REGISTRY }}/${{ secrets.GCP_IMAGE_NAME }},ghcr.io/${{ github.repository }}"
