name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: live

    steps:
      - uses: actions/checkout@v3
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: deploy/container/Dockerfile
          push: true
          tags: "${{ secrets.GCP_IMAGE_TAG }},ghcr.io/${{ github.repository }}"
