name: Server Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry self add 'poethepoet[poetry_plugin]'
          poetry install
      - name: Check formatting
        run: poetry poe format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry self add 'poethepoet[poetry_plugin]'
          poetry install
      - name: Lint
        run: poetry poe lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry self add 'poethepoet[poetry_plugin]'
          poetry install
      - name: Type check
        run: poetry poe type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: |
          poetry self add 'poethepoet[poetry_plugin]'
          poetry install
      - name: Run tests
        run: poetry poe test -v
